name: Check Student Code

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test_student_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run student code
        run: python check.py

      - name: Decode and extract archive
        run: |
          echo "${{ secrets.FILES_BASE64 }}" | base64 --decode > files.zip
          unzip files.zip
          cat "Котлован. Андрей Платонов.txt"
